drop table snu.musica_leiturasassociadas;
drop table snu.musica_tipos;
drop table snu.musica_associacoes;
drop table snu.documentomusica_listainvertida;
drop table snu.documentomusica_vocabulario;
drop table snu.missas_musicas;
drop table snu.musica;
drop table snu.musica_documento;
drop table snu.musica_autores;